import './styles/variables.css';
import './styles/base.css';
import './styles/layout.css';
import './styles/components.css';
import { mountApp } from './app.js';

mountApp(document.getElementById('app'));

// Register service worker for PWA (generated by vite-plugin-pwa at build time)
if ('serviceWorker' in navigator && import.meta.env.PROD) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {
      /* silent fail — app still works without offline support */
    });
  });
}
